#language: java
#jdk: oraclejdk8

#before_install:
#  - cd WalkLive/Server  
osx_image: xcode9.0.1
language: objective-c

xcode_project: 2017-group-14/Walklive/Walklive.xcworkspace

# whitelist
branches:
only:
- master
