USE walklive;

DROP TABLE IF EXISTS Trips, users, friendrequests;



CREATE TABLE Trips (TRIP_ID INT PRIMARY KEY, STARTTIME VARCHAR);
CREATE TABLE users(Id TEXT PRIMARY KEY URER_NAME, PASSWORD TEXT);

CREATE TABLE friendrequests(Id TEXT RIMARY KEY USER_NAME);

INSERT INTO Trips(Id, STARTTIME) VALUES(1, 'Jack London');