# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Walklive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Walklive
    pod 'AFNetworking'

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'GoogleMaps'
pod 'GoogleSignIn'

  target 'WalkliveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WalkliveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
